<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Auth;
use App\User;
use App\Post;
use App\Research;
use App\Userprofile;
use App\Orgprofile;


class Attachment extends Model
{
    //
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name','owner','user_id', 'org_id','research_id','post_id',
    ];

    public static function boot()
    {
        /*
        $userprofile = userprofile::find($id);
        $orgprofile = orgprofile::find($id);
        $post = post::find($id);
        $research = Research::find($id);*/
        // parent::boot(); // TODO: Change the autogenerated stub
        static::saving(function ($table) {
            $table->owner = Auth::user()->userName; 
            // $table->research_id = $research->id;
        });
    }

    public function user() {
    	return $this->belongsTo(User::class);
    }

    public function userprofile() {
    	return $this->belongsTo(Userprofile::class);    	
    }

    public function orgprofile() {
    	return $this->belongsTo(Orgprofile::class);    	
    }

    public function research() {
    	return $this->belongsTo(Research::class);    	
    }

    public function post(){
    	return $this->belongsTo(Post::class);    	
    }
}
